/** Consistent hover explanations for statistics shown throughout the web app. */
export const STAT_DESCRIPTIONS = {
  role: 'Effective preferred matchup role for this game.',
  timePlayed: 'Time played from pull release until the point ends, excluding recorded stoppages.',
  pointsPlayed: 'Number of points played.',
  offensePointsPlayed: 'Points played that started with our team on offense.',
  offenseWinPercentage: 'Percentage of offense-starting points that our team won.',
  defensePointsPlayed: 'Points played that started with our team on defense.',
  defenseWinPercentage: 'Percentage of defense-starting points that our team won.',
  completions: 'Completed passes thrown, including scoring passes.',
  throwingPercentage: 'Completed passes divided by all recorded throws, including turnovers.',
  receptions: 'Completed passes received, including goals.',
  receivingPercentage: 'Receptions divided by all recorded targets with a known intended receiver.',
  drops: 'Turnovers recorded as a drop and charged to this intended receiver.',
  touches: 'Times this player gained possession from a pickup, completion, or goal reception.',
  turnoversPerTouch: 'Turnovers charged to this player divided by recorded touches.',
  turnovers: 'Turnovers charged to this player or recorded during this line’s points.',
  goals: 'Goals caught.',
  assists: 'Passes caught for a goal by a teammate.',
  hockeyAssists: 'Passes immediately before the scoring assist.',
  blocks: 'Defensive blocks credited to a player or line.',
  pulls: 'Pulls credited at the start of defensive points.',
  plusMinus: 'Goals for minus goals against while this player or line was active.',
  discTime: 'Estimated time holding the disc between recorded events, excluding stoppages.',
  goalsFor: 'Points scored by our team.',
  goalsAgainst: 'Points scored by the opponent.',
  cleanHolds: 'Offense-starting points won without a tracked-team turnover.',
  holdRate: 'Offense-starting points won divided by offense-starting points played.',
  breakRate: 'Defense-starting points won divided by defense-starting points played.',
  defensiveConversion: 'Opponent possessions won that led to our goal before our next turnover.',
  connectionAttempts: 'Throws with both a known thrower and intended receiver.',
  connectionPercentage: 'Completed passes divided by attempts for this thrower–receiver pairing.',
  score: 'Final recorded score for the game.',
  matchupPoints: 'Point results grouped by the seven-player preferred matchup at the pull.',
  pointStart: 'Whether our team started the point on offense or defense.',
  initialDefense: 'The defense used when the point began.',
} as const;
