/** Consistent hover explanations for statistics shown throughout the web app. */
export const STAT_DESCRIPTIONS = {
  role: 'Effective preferred matchup role for this game.',
  gamesPlayed: 'Games in which this player has a recorded point or contribution.',
  timePlayed: 'Time played from pull release until the point ends, with substitutions respected.',
  timePerPoint: 'Recorded playing time divided by points played.',
  pointsPlayed: 'Number of points played.',
  offensePointsPlayed: 'Points played that started with our team on offense.',
  offenseWinPercentage: 'Percentage of offense-starting points that our team won.',
  defensePointsPlayed: 'Points played that started with our team on defense.',
  defenseWinPercentage: 'Percentage of defense-starting points that our team won.',
  completions: 'Completed passes thrown, including scoring passes.',
  throwingPercentage: 'Completed passes divided by all recorded throws, including turnovers.',
  passingPercentage: 'Recorded throws minus passer turnovers, divided by recorded throws. Drops do not count against the passer.',
  receptions: 'Completed passes received, including goals.',
  receivingPercentage: 'Receptions divided by all recorded targets with a known intended receiver.',
  drops: 'Turnovers recorded as a drop and charged to this intended receiver.',
  passerTurnovers: 'Non-drop turnovers charged to the passer, including throwaways, stalls, blocks, and miscellaneous reasons.',
  throwaways: 'Passer turnovers specifically recorded as throwaways.',
  stalls: 'Passer turnovers specifically recorded as stalls.',
  touches: 'Times this player gained possession from a pickup, completion, or goal reception.',
  turnoversPerTouch: 'Turnovers charged to this player divided by recorded touches.',
  turnovers: 'Turnovers charged to this player or recorded during this line’s points.',
  goals: 'Goals caught.',
  assists: 'Passes caught for a goal by a teammate.',
  hockeyAssists: 'Passes immediately before the scoring assist.',
  blocks: 'Defensive blocks credited to a player or line.',
  pulls: 'Pulls credited at the start of defensive points.',
  plusMinus: 'Goals for minus goals against while this player or line was active.',
  extendedPlusMinus: 'Goals, assists, and Ds are +1; drops and passer turnovers are −1. A Callahan is +2 and being Callahaned is −1.',
  offenseEfficiency: 'Net point results while active at the score on points that began with our team receiving: +1 for a goal and −1 for a break against.',
  defenseEfficiency: 'Net point results while active at the score on points that began with our team pulling: +1 for a break and −1 for an opponent goal.',
  breaks: 'Defense-starting points won while this player participated.',
  discTime: 'Estimated time holding the disc between recorded events, excluding stoppages.',
  discPerPoint: 'Recorded time with the disc divided by points played.',
  perGame: 'Total divided by games with a recorded point or contribution.',
  perTenPoints: 'Total normalized to 10 points played.',
  goalsFor: 'Points scored by our team.',
  goalsAgainst: 'Points scored by the opponent.',
  cleanHolds: 'Offense-starting points won without a tracked-team turnover.',
  holdRate: 'Offense-starting points won divided by offense-starting points played.',
  breakRate: 'Defense-starting points won divided by defense-starting points played.',
  defensiveConversion: 'Opponent possessions won that led to our goal before our next turnover.',
  connectionAttempts: 'Throws with both a known thrower and intended receiver.',
  connectionPercentage: 'Completed passes divided by attempts for this thrower–receiver pairing.',
  score: 'Final recorded score for the game.',
  matchupPoints: 'Point results grouped by the seven-player preferred matchup at the pull.',
  pointStart: 'Whether our team started the point on offense or defense.',
  initialDefense: 'The defense used when the point began.',
} as const;
