/** Consistent hover explanations for statistics shown throughout the web app. */
export const STAT_DESCRIPTIONS = {
  role: 'Effective preferred matchup role for this game.',
  timePlayed: 'Time played from pull release until the point ends, excluding recorded stoppages.',
  pointsPlayed: 'Number of points played.',
  offensePointsPlayed: 'Points played that started with our team on offense.',
  offenseWinPercentage: 'Percentage of offense-starting points that our team won.',
  defensePointsPlayed: 'Points played that started with our team on defense.',
  defenseWinPercentage: 'Percentage of defense-starting points that our team won.',
  completions: 'Completed passes thrown, including scoring passes.',
  receptions: 'Completed passes received, including goals.',
  turnovers: 'Turnovers charged to this player or recorded during this line’s points.',
  goals: 'Goals caught.',
  assists: 'Passes caught for a goal by a teammate.',
  hockeyAssists: 'Passes immediately before the scoring assist.',
  blocks: 'Defensive blocks credited to a player or line.',
  pulls: 'Pulls credited at the start of defensive points.',
  plusMinus: 'Goals for minus goals against while this player or line was active.',
  discTime: 'Estimated time holding the disc between recorded events, excluding stoppages.',
  goalsFor: 'Points scored by our team.',
  goalsAgainst: 'Points scored by the opponent.',
  score: 'Final recorded score for the game.',
  matchupPoints: 'Point results grouped by the seven-player preferred matchup at the pull.',
  pointStart: 'Whether our team started the point on offense or defense.',
  initialDefense: 'The defense used when the point began.',
} as const;
